#!/usr/bin/python
#coding: utf-8

fone = input()
fone = fone.replace("A","2")
fone = fone.replace("B","2")
fone = fone.replace("C","2")
fone = fone.replace("D","3")
fone = fone.replace("E","3")
fone = fone.replace("F","3")
fone = fone.replace("G","4")
fone = fone.replace("H","4")
fone = fone.replace("I","4")
fone = fone.replace("J","5")
fone = fone.replace("K","5")
fone = fone.replace("L","5")
fone = fone.replace("M","6")
fone = fone.replace("N","6")
fone = fone.replace("O","6")
fone = fone.replace("P","7")
fone = fone.replace("Q","7")
fone = fone.replace("R","7")
fone = fone.replace("S","7")
fone = fone.replace("T","8")
fone = fone.replace("U","8")
fone = fone.replace("V","8")
fone = fone.replace("W","9")
fone = fone.replace("X","9")
fone = fone.replace("Y","9")
fone = fone.replace("Z","9")

print(fone)
